# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPwoG_bEIJA-X4oOijztaJmEpq75Va7R
"""



import random #random modülünü çalıştırmak için aktif ediyoruz.
def tas_kagit_makas_elif_zehra_canbulat():
  print(' oyunda herkes taş, kağıt ve makastan birini seçer. taş, makası kırar. kağıt taşı sarar ve makas kağıdı keser.')
  oyun_tekrari = 'evet'
  while oyun_tekrari == 'evet': #oyuncu evet derse oyunu tekrak başlatmak için evet cevabı geldiği sürece dönecek döngü. geniş kapsamlı döngümüz
    player_puan = 0
    bilgisayar_puan = 0
    tur_sayisi = 0
    while player_puan < 2 and bilgisayar_puan < 2: # kimsenin puanı 2 değilken döngü başlar. ilk döngümüzn içine 2. döngüyü ekliyoruz.
      player = input('taş, kağıt veya makas seçiniz:')
      bilgisayar = random.choice(['taş' , 'kağıt' , 'makas']) #verilen liste içinden herhangi birini seçmesi için random.choice fonksiyonunu kullandık.
      tur_sayisi += 1
      if player == bilgisayar:
        player_puan += 0
        bilgisayar_puan += 0
        tur_sayisi += 1
        print(f"Oyuncunun seçimi: {player}, bilgisayarın seçimi: {bilgisayar}. Kimse puan alamadı")
      elif player == 'taş':
        if bilgisayar == 'kağıt':
          bilgisayar_puan += 1
          tur_sayisi += 1
          print(f'bilgisayar kağıt seçti, player puan: {player_puan} ,bilgisayar puan: {bilgisayar_puan} ')
        else:
          player_puan += 1
          print(f'bilgisayar makas seçti, player puan: {player_puan} ,bilgisayar puan: {bilgisayar_puan} ')
          tur_sayisi += 1
      elif player == 'kağıt':
        if bilgisayar == 'makas':
          bilgisayar_puan += 1
          tur_sayisi += 1
          print(f'bilgisayar makas seçti, player puan: {player_puan} ,bilgisayar puan: {bilgisayar_puan} ')

        else:
          player_puan += 1
          tur_sayisi += 1
          print(f'bilgisayar taş seçti, player puan: {player_puan} ,bilgisayar puan: {bilgisayar_puan} ')

      elif player == 'makas':
        if bilgisayar == 'taş':
          bilgisayar_puan += 1
          tur_sayisi += 1
          print(f'bilgisayar taş seçti, player puan: {player_puan} ,bilgisayar puan: {bilgisayar_puan} ')

        else:
          player_puan += 1
          tur_sayisi += 1
          print(f'bilgisayar kağıt seçti, player puan {player_puan} ,bilgisayar puan: {bilgisayar_puan} ')

    if tur_sayisi == 2 and bilgisayar_puan == 2:
      print('bir dahaki sefere, bilgisayar kazandı.')
    elif tur_sayisi == 2 and player_puan == 2:
      print('tebrikler! çok iyisiniz, kazandınız.')
    elif bilgisayar_puan == 2:
      print('bilgisayar kazandı')
      break
    elif player_puan == 2:
      print('tebrikler! çok iyisiniz, kazandınız.')
      break

    oyun_tekrari = input('tekrar oynamak ister misin , evet ya da hayır: ') # ilk while döngüsü içinde olduğu için evet cevabı yazdığımız sürece çalışacak ve oyun tekrar oynanacak. 2. while dögüsü ilk yazdığımızın içinde olduğu için onlar da dönmeye devam edecek.
  print("Oyun bitti")
tas_kagit_makas_elif_zehra_canbulat()


""